### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by 11140321** [zjujdj/InteractionGraphNet#4]
我想问一下，为什么运行完一个epoch之后会出现这样的错误？
epoch:0 	 train_rmse:7.3017 	 valid_rmse:6.7257 	 time:48.230 s
Traceback (most recent call last):
  File "D:/DT/InteractionGraphNet-master/codes/ign_train.py", line 184, in <module>
    valid_true, valid_pred, _ = run_a_eval_epoch(DTIModel, valid_dataloader, device)
  File "D:/DT/InteractionGraphNet-master/codes/ign_train.py", line 54, in run_a_eval_epoch
    outputs = model(bg, bg3)
  File "F:\anaconda1\envs\torchcpu\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\DT\InteractionGraphNet-master\codes\model.py", line 409, in forward
    atom_feats = bg.ndata.pop('h')
  File "F:\anaconda1\envs\torchcpu\lib\_collections_abc.py", line 795, in pop
    value = self[key]
  File "F:\anaconda1\envs\torchcpu\lib\site-packages\dgl\view.py", line 60, in __getitem__
    return self._graph.get_n_repr(self._nodes)[key]
KeyError: 'h'

**Comment by zjujdj** [comment]
@11140321 
我感觉可能是你的数据有问题？或者你调调batch_size看看？
